### ISSUE TITLE
A lot of whitespace on 640 wide devices.. (Nice to have)

### ISSUE THREAD

**Issue by Thelle** [bemyeyes/bemyeyes-website#17]
Just looks like a lot when sitting with the device.. Tiny thing, i know.. ![2015-01-12 20 51 11](https://cloud.githubusercontent.com/assets/1733883/5709885/bdd219f6-9a9d-11e4-8136-819f645ad17a.png)

**Comment by ksmandersen** [comment]
I agree. I'll see if can fix this before the launch

**Comment by mbogh** [comment]
![screen shot 2015-01-13 at 14 03 25](https://cloud.githubusercontent.com/assets/736606/5721057/0404cefc-9b2d-11e4-8f3b-ada630cca989.png)
