### ISSUE TITLE
Images and icons looks blurry on iPhone 6 (iOS 8.1.2) in Safari

### ISSUE THREAD

**Issue by mbogh** [bemyeyes/bemyeyes-website#18]
As the subject suggests, I find the images and icons rather blurry when viewed on my iPhone 6.

It seems that the only icon/image that is non blurry is the play icon for the video.

![2015-01-15 11 09 36](https://cloud.githubusercontent.com/assets/736606/5756284/fec7de70-9cad-11e4-88ac-0c4a04e473fa.png)
![2015-01-15 11 09 14](https://cloud.githubusercontent.com/assets/736606/5756286/fef7d9c2-9cad-11e4-9bd4-35d7ecf23e2c.png)
![2015-01-15 11 08 55](https://cloud.githubusercontent.com/assets/736606/5756285/fef6f8f4-9cad-11e4-8836-ef72eb296beb.png)

**Comment by mbogh** [comment]
Seems to be related to https://github.com/imulus/retinajs/issues/40

Suggestion is using data-at2x="".

**Comment by ksmandersen** [comment]
Ahh yes. This problem again. It's because the domain of the CDN stored file is not the same as the sites.

**Comment by ksmandersen** [comment]
Tried to use the data-at2x property but the problem persists. Will investigate

**Comment by ksmandersen** [comment]
Updating retina.js to the latest version solved the issue

**Comment by mbogh** [comment]
Sharp again :+1:
