### ISSUE TITLE
iPad - Playback of video can't be stopped - audio continues

### ISSUE THREAD

**Issue by Thelle** [bemyeyes/bemyeyes-website#22]

**Comment by motte** [comment]
It seems fine for an iPhone 6+ Safari.

**Comment by Thelle** [comment]
Confirmed on iPad Air - don't seem to be issue on iPhone.. (found to be fine on iPhone 5)

**Comment by ksmandersen** [comment]
Not sure what to do about this. It's a native HTML5 video player

**Comment by motte** [comment]
You could try manually pausing via Vimeo JS Frogaloop API: http://developer.vimeo.com/player/js-api

Repo: https://github.com/vimeo/player-api/tree/master/javascript

**Comment by ksmandersen** [comment]
@motte The vimeo video is not used on iPad / iPhone. We use a standard HTML5 video tag. Refer to https://github.com/bemyeyes/bemyeyes-website/blob/master/assets/js/main.coffee#L54-L61

**Comment by motte** [comment]
Even better.  Use the HTML5 API before:

    var $vid = $(".video-wrapper");
    
    function pauseVideo() {
        $vid.pause();
    }

Again, it seems to work in iPhone and I don't have an iPad, so I can't test.

**Comment by Thelle** [comment]
The playback is a lot better, but still we experience disrupted playback. 
Proposed solution: use 360p video

**Comment by ksmandersen** [comment]
If you encode a 360p I'll upload it and we can try it out

**Comment by ksmandersen** [comment]
What is the status on this @Thelle . Cannot move forward until I have a 360p version of the file
