### ISSUE TITLE
iOS Safari App Banner

### ISSUE THREAD

**Issue by duemunk** [bemyeyes/bemyeyes-website#23]

**Comment by motte** [comment]
Sent in pull request.

**Comment by ksmandersen** [comment]
I'm not really sure about this. An app banner is really spammy. Please include Michael in the decision about this

**Comment by motte** [comment]
It's the apple smart app banner that only appears on iOS browsers.

**Comment by duemunk** [comment]
Hi motte. We are aware of this, but since website already has a "Download the App" right at the top, the banner might not be necessary. Many user find the banner spammy, which is the main reason for not using it.

**Comment by motte** [comment]
Makes sense.  Closed pull request

**Comment by plainspace** [comment]
Can you close the issue too?
