### ISSUE TITLE
Afbrudt afspilning på mobil (Critical)

### ISSUE THREAD

**Issue by Thelle** [bemyeyes/bemyeyes-website#3]
Afbrudt afspilning på mobil selv på high bandwidth wifi.

Mulig løsning: I første omgang kan vi gå tilbage til vimeo på mobil selv om det så kræver 2 tryk - alternativt prøve 480/360p med bedre komprimering.

**Comment by ksmandersen** [comment]
Jeg synes vi skal prøve med en 480p version

**Comment by ksmandersen** [comment]
We will try to use CloudFront

**Comment by ksmandersen** [comment]
Jeg har prøvet at sætte vimeo player på i stedet for, men jeg kan slet ikke få den til at afspille. Den har mange andre problemer også. Jeg synes at vi skal bevare den her løsning i stedet for. Kan I lave mig en 480p version i stedet for som jeg kan uploade?

**Comment by Thelle** [comment]
Eneste issue jeg kan se er at der skal dobbelt tryk til.. I will let you be the judge - bare super vigtig det ikke hakker på midt range US 3G forbindelse :)
https://www.dropbox.com/s/v48blxou8ex80kn/FINAL_CUT%201.2.2_480p.mp4?dl=0
https://www.dropbox.com/s/s8zmwjuc2ql3lu6/FINAL_CUT%201.2.2_360p.mp4?dl=0

**Comment by Thelle** [comment]
Vimeo embed på computer ser iøvrigt ikke ud centeret længere..? 
![screenshot 2015-01-15 01 33 48](https://cloud.githubusercontent.com/assets/1733883/5750532/a3710da0-9c56-11e4-9efb-b1973ddd9c4b.png)

**Comment by ksmandersen** [comment]
Minor detail

**Comment by Thelle** [comment]
Think it works better with for example itsbreaking.com with just the vimeo video

**Comment by ksmandersen** [comment]
I'll look into doing that when I get the time
