### ISSUE TITLE
/help a page to show how you can help

### ISSUE THREAD

**Issue by Thelle** [bemyeyes/bemyeyes-website#39]
after mailchimp or beta signup

**Comment by higiacomo** [comment]
Hi Thelle!

I'd like to make this page this week :)

Here's a first draft, please leave your comments! even if it has to be redone from zero.. it's easier to start discussion with something in front of us

http://invis.io/ZD2G5Q4BN

Make sure to toggle comments (bottom right of the page)

Cheers :)
Giacomo

**Comment by Thelle** [comment]
Looks awesome! - I think you can go ahead! Some kind of icons for the first three headlines would be great - go have a look at iconfinder.com

**Comment by higiacomo** [comment]
All right, icons added and tomorrow I can code it : )
http://invis.io/ZD2G5Q4BN

How about the final copy/wording?
Is there someone who can review it?
If so.. they could just add comments to the design with the revised copy

**Comment by duemunk** [comment]
Maybe @idamariepiper or @chiepaaa can look at the copy?

**Comment by chiepaaa** [comment]
@duemunk @higiacomo Here is the corrections from Madison (native speaker) and I reviewed it too, looks great now :)

How can YOU help?

Be My Eyes is a non-profit, put on this planet to make a positive impact on the lives of blind people. We fully rely on donations and volunteers to sustain our operations. So here’s how you can help:

Become a sighted volunteer

Be My Eyes could not exist without sighted volunteers. If you have time and an iOS device, download the app and lend your eyes to the blind.

Translate into your language

You can help translate Be My Eyes into your native language. Getting started is easy and unbinding. Click here to start translating.

Donate to the project

To keep our servers running, we face a fixed cost every month. Will you help us meet the cost? Donate via PayPal or Credit Card.

Can’t commit? Just share BeMyEyes with your friends

Are you a developer?

Android developer?
We’re bringing Be My Eyes to Android. Speed up the development on GitHub.

iOS or Backend developer?
Be My Eyes is open source. View and contribute to the code on GitHub.

**Comment by higiacomo** [comment]
Great
I made the pull request.

**Comment by ksmandersen** [comment]
This is live now.
