### ISSUE TITLE
display global reach (flags/map)

### ISSUE THREAD

**Issue by Thelle** [bemyeyes/bemyeyes-website#41]

**Comment by ksmandersen** [comment]
Could be a fun thing to visualize. Maybe @higiacomo has an idea for this?

**Comment by higiacomo** [comment]
Yeah I'd like to visualise something! But while it's fun.. it's probably not a priority :8ball: 

I suggested something here maybe you can comment?
https://github.com/bemyeyes/bemyeyes-website/issues/56
