### ISSUE TITLE
Improved navigation

### ISSUE THREAD

**Issue by Thelle** [bemyeyes/bemyeyes-website#5]
* Home link i nav-bar når man er på en underside
* Indikation af hvilken side man er på

**Comment by ksmandersen** [comment]
Det er super forvirrende at have et home link kun på undersider. Som på de fleste andre hjemmesider så kommer man til forsiden ved at klikke på BeMyEyes ikonet.

**Comment by ksmandersen** [comment]
Det er relativt svært at lave en indikation af hvilken side man er på med det statiske HTML vi har

**Comment by Thelle** [comment]
ok :)
