### ISSUE TITLE
Update the FAQ

### ISSUE THREAD

**Issue by chiepaaa** [bemyeyes/bemyeyes-website#52]
### How did the idea come about?
Hans Jørgen Wiberg, who is visually impaired himself, came up with the idea for the application. Through his work at the “Danish Blind Society” he recognized, that blind people often need help to cope with smaller everyday tasks, where a “pair of eyes” could make a significant difference. In April of 2012 he presented the idea for an application at a startup event in Denmark. At this event he met the rest of the Be My Eyes (BME) team, and together they won the price for "the most innovative idea". Since 2012 the BME team has worked hard to make the app a reality. The app was launched the 15th of January 2015.

### What is Be My Eyes good for?
I know what you’re thinking – blind people are so badass, they don’t need help! And it’s true! They navigate entire cities on their own, blind! But even though blind people often have four supersonic senses left, they’re not Sherlocks, and they need help once in a while! BME app hopes to provide that help.

### What is an open source? 
Open source means that the source code (how the app is build in coding) is free to use, change, distribute or whatever you would like to do with it! You will find the code on GitHub (https://github.com/bemyeyes). The reason we have chosen open source, is because we want to share the concept of BME and give talented people the chance to improve it by contributing with new features or fixation of bugs.

### How do visually impaired people use an iPhone?
The iPhone has a feature called VoiceOver (https://www.apple.com/accessibility/ios/voiceover/) which enables people with impaired vision to use an iPhone with synthetic speech and touch-based interface. Particularly, iPhone has been perceived as one of the best assisting devices for the visually impaired. It has been widely used as a GPS, to get information about transportation, receive news and much, more. If you would like to  learn more about it, you are welcome to check out the video(https://www.youtube.com/watch?v=c0nvdiRdehw) made by Tommy Edison, on how visually impaired people use an iPhone.

### How is the application financed?
BME is a non-profit organization, thereby the costs related to keeping it up and running depends on external funding. We do not receive any funding from advertising, and are not planning to consider it as a means for financing the application in the future. The organization received the main seed funding from the Velux Foundation, and some additional funding from the Danish Association of the Blind, the Blind Foundation in Denmark and the IndiGoGo - crowd funding campaign. By September 2015 the initial funding comes to an end, which is why we are working on a more sustainable business model for the future. We are considering a subscription model, sponsorships or donations and, therefore, we are more than grateful for any ideas or help coming our way.

### How do I get started?
Find and download the app from the Apple's app store, follow the instructions in the app to create a profile and add languages, then you should be ready to call or receive a call, without even having the app opened or in the background.

### What are the points and levels for in the app? 
The points are awarded to you by using the app, answering calls and sharing on different media. They are not required to be able to help, and merely work as an incentive. The "levels" indicate your level of experience based on the points. For now, it is merely for yourself to see, however, in future, we are planning to use the system for indicating and pairing most promising helpers.

### How can I change/add more languages? 
You can choose the languages in settings. Here you can also set up several languages, or change the languages you have chosen before. We are working on implementing several new language editions, which will be available with the next updates. 

### Why don't I get requests for help? 
We are very thankful, that you have signed up, however, since there are more than ten times the amount of seeing helpers, than there are blind users, it might take a longer time to receive a call. Nonetheless, we are grateful to see the impressive amount of people willing to help, so please keep your patience, a call will definitely come at some point.

### When I receive a request for help, what should I do?
When you receive a call for assistance, it will look like as if you get a notification. You answer the call by tapping the request or swiping it right.

### How do you prevent misuse/abuse?
Unfortunately, as with any app,cases of misuse/abuse is almost impossible to detect in forehand, therefore, we kindly ask users to report it right after the call by the ''abuse'' button in the app when such behaviour is being noticed. Please make sure when you report someone, as it will result in an exclusion from the network. 

### How do I make sure, that I am not notified during the night? 
The standard setting only allows you to receive calls from 7 in the morning (7am) to 10 in the evening (10pm) in your local time zone. Therefore, you do not have to worry to receive calls in the middle of the night. We are working on an opportunity to personalise the time availability settings, which will hopefully come out next.

### How can I upload a photo to my profile?
If you have created an account using your email, unfortunately, you are not able to insert a photo. It is not your device that is causing this problem, but a bug, which we are trying to fix. However, if you sign up with your Facebook account, your Facebook picture should be automatically added to your profile.

### What should I do, if I am seeing a wrong Facebook profile picture?
There has been a bug regarding this feature in the app, we truly apologize for it. Nevertheless, we have been working hard to fix it and it should be working appropriately with the next update of the app, so just keep your patience with us.

### Do I need a twitter account in order to help? 
You do not need a twitter account to help, it only provides you with more points if you have it, but it does not restrict or anyhow affect your ability to help. 

### Do I need to have the app open in order to receive a call?
No. You are ready to receive a call as soon as you have created your account, and are logged in. You do not even need the app to be opened or running in the background. The standard setting on the app for receiving calls is from 7 in the morning (7am) to 10 in the evening (10pm) in your local time zone. If you do not want to receive the calls during certain time, you can log-out or use the ''do not disturb'' function in your phone.

### I accepted a request to help/asked for help, but the app says I have to wait for a connection, what should I do?
If you are calling or answering a call and you receive a message  "waiting to connect", it should not take longer than a minute, however if it takes longer than that, you should disconnect. In case, you are a visually impaired user, please try to re-dial. Due to the massive traffic of helpers trying to answer calls simultaneously, there still might occur some system problems, however we are working on decreasing them with each update. Please make sure you have a strong signal and a steady connection, as the application requires some bandwidth to show video in a sufficient quality.

### What should I do,  if the application is unresponsive?
If the application is unresponsive, it most probably is due to server problems. Do not worry, they will get fixed ASAP, and please try it again later. 

### What should I do,  if my app crashes when I try to  use it or open it?
If you are experiencing this when trying to open the app, please, try to open it one more time or delete the app and download it again. If it is crashing while trying to login with Facebook, go to system settings and make sure that the Be My Eyes app has access to your Facebook account. If the app still crashes, please let us know, we are trying to fix it continuously. 

### What should I do, if I cannot log-in again or log-on using a secondary device? 
Please find the button on the first screen of the app "Already registered? Log in here." It is written with smaller letters and might be easy to miss, however we will make it more user friendly by time.

### How about an Android or Windows version?
Currently, the Be My Eyes application is available only for iOS, however, an Android version is currently under development, but still without an estimated launch date. If you would like to be amongst the first ones to get notified about it, please, sign up at  bemyeyes.org/android. Regarding a Windows version, we have not set any plans for development yet, however depending on the future direction, it might be a consideration. Nonetheless, if you would like to participate in making  Be My Eyes a client for another platform, please check out our GitHub repository (https://github.com/bemyeyes) or get in touch on Twitter (https://twitter.com/BeMyEyes). 

### Is it possible to use the BME video?
You are more than welcome to use our video, however, when doing so, please embed it. The video can be found on vimeo (https://vimeo.com/113872517). If you are not able to do so, you should provide a link to our website and the application in your description accompanying the video. You can format it in HTML or any other way you prefer.

### How can I become a sighted helper in the app?
For becoming a sighted helper you simply need to download the application, register and you are ready to help. To be able to download the application you will need an iPhone 4 or newer. 

### How can I become a case person?
We have been receiving a broad media coverage after the launch and therefore, are constantly looking for users around the world using the application and willing to share their experience on BME. So, if you would like to become a case person and share your story, please write us an email on mystory@bemyeyes.org providing your story together with some contact information about yourself (name, mail, phone, country/city).

### How can I become an active volunteer?
Volunteering for Be My Eyes is easy and unbinding. If you would like to help us with the translations for the application, please visit the page crowdin(https://crowdin.com/project/bemyeyes), where you will find all the languages for the application and the progress on their respective translations. You are welcome to participate on further translations or on the verification of the existing ones. Thank you so much for all your help in forehand, as being a small team, we really appreciate all the help we can get.

### How can I help spread the word about the BME?
Being a small organization trying to to get noticed all around the world has its challenges, therefore we encourage everyone to help us spread the word about the application. Please, follow us on Twitter(https://twitter.com/BeMyEyes) and Facebook (https://www.facebook.com/bemyeyes.org), if you would like contact us regarding media coverage, please send us an email on press@bemyeyes.org, if you are a member of  any organization or foundation for visually impaired, please spread the word in your network or community. 

### How can I donate for the BME organization? 
If you would like to donate for the organization, you can do so on the homepage. We are extremely thankful for all the donations, which help us keep the application running. If you would like to contact us for the possibility of partnership, please send us an email on press@bemyeyes.org. 

### How do I delete my account? 
You cannot delete your account in the app, if you would like to get it deleted, please send us an email on info@bemyeyes.org.

### Your question is not listed? 
If your question is not answered here, please  email us at info@bemyeyes.org or catch us on Twitter(https://twitter.com/BeMyEyes) or Facebook(https://www.facebook.com/bemyeyes.org).

**Comment by duemunk** [comment]
2-3 sentences should be max. Else split questions.

**Comment by chiepaaa** [comment]
Ok, now it should be ready to go up on website, who do I need to write about that?! Btw, it had hyperlinks in the document, can they still be in the website as well? you can't see them in the github though.

**Comment by ksmandersen** [comment]
Are these questions supposed to replace the existing questions or compliment them? Also please add any missing links so that I don't have to manually go through and carefully merge the changes in

**Comment by ksmandersen** [comment]
I'd also love to get @Thelle's input

**Comment by Thelle** [comment]
I have not had the time to read through it throughly, but I feel confident that the text above is better that what we currently have on our website, and that it therefore should be implemented asap.

@chiepaaa have you also read though the current FAQ on the website - making sure we don't miss out on something good from that?

**Comment by chiepaaa** [comment]
@Thelle @ksmandersen these questions should replace the ones on website, because they are already included in the new file. I have included all the links here, right after the words I liked them to be hyperlinked to, hope that works.

**Comment by duemunk** [comment]
@ksmandersen Can I help preparing this for the website?

**Comment by ksmandersen** [comment]
@duemunk Sure thing. If you replace the questions in the [faq/index.html](https://github.com/bemyeyes/bemyeyes-website/blob/master/faq/index.html) file with the ones above then I can deploy a new version with those changes
