### ISSUE TITLE
Add a section with team members

### ISSUE THREAD

**Issue by duemunk** [bemyeyes/bemyeyes-website#57]
Something simple like this.
![screen shot 2015-04-21 at 17 43 00](https://cloud.githubusercontent.com/assets/489138/7256155/ece20776-e84d-11e4-9cad-e267e6de75ec.png)

Circular images with name and title.

![17ebc7c](https://cloud.githubusercontent.com/assets/489138/7256356/dfc29b36-e84e-11e4-8f92-a530b4476c4e.jpg)
Christian Erfurt, CEO
![img_3842](https://cloud.githubusercontent.com/assets/489138/7492760/a94a5d42-f3fb-11e4-92f4-7b76761a8d97.JPG)
Hans Jørgen Wiberg, Co-Founder and Chairman of the Board
![ida_bemyeyes](https://cloud.githubusercontent.com/assets/489138/7491658/ae1ed22c-f3eb-11e4-9ac3-084649a1e4b8.jpg)
Ida Marie Piper, PR and Communication Manager
![tobias profil](https://cloud.githubusercontent.com/assets/489138/7256379/063b85a2-e84f-11e4-9cae-b160544b08c6.JPG)
Tobias Due Munk, iOS Developer
![11211664_938557582873041_2120541711_o](https://cloud.githubusercontent.com/assets/489138/7492435/6de70654-f3f8-11e4-816e-008f24c8b00f.jpg)
Ruta Pukite, Communication Intern

**Comment by higiacomo** [comment]
@duemunk
Happy to work on this, where can I get a more or less complete list of people?

**Comment by ksmandersen** [comment]
Like this idea :+1:

**Comment by duemunk** [comment]
@higiacomo Awesome! If you make it work responsive with 2-4 people per row, we'll just add a more complete list when you're close to done.

**Comment by duemunk** [comment]
Add it between sections with testimonial and social. Use a coloured background (brown as top or blue gradient) with pure white text. Probably much like the app with white border as well:
![screen shot 2015-04-22 at 10 42 26](https://cloud.githubusercontent.com/assets/489138/7270413/599a540c-e8dc-11e4-9eb8-bc9093aeb643.png)

**Comment by higiacomo** [comment]
Something like this?

![aboutsection](https://cloud.githubusercontent.com/assets/874876/7297452/48689cdc-e9c9-11e4-96b0-564a5c321766.png)

**Comment by higiacomo** [comment]
here with the quote aligned 
![aboutsection-quote-aligned](https://cloud.githubusercontent.com/assets/874876/7297538/e3b421e8-e9c9-11e4-895e-2bb5c290501f.png)

**Comment by duemunk** [comment]
Wow, that was quick :) looks awesome!!




Here you have some extra white space to add between sections



:P

**Comment by higiacomo** [comment]
All right I'll code it next week then
In the meantime having list of people+picture would be a good idea :8ball:

**Comment by duemunk** [comment]
I think the list is done for now @higiacomo. Thanks for your awesome work!

**Comment by higiacomo** [comment]
cheers @duemunk 
should I add the people above or you do it?

(also could you look at https://github.com/bemyeyes/bemyeyes-website/issues/58)

**Comment by duemunk** [comment]
Oh I missed your comment. I would very much appreciate it if you added the people above :)

**Comment by higiacomo** [comment]
updated the pull request with pics and info's
didn't want to go on a second row for just 1 person and 5 cols would look cramped so the Ruta isn't there

Maybe we can add some people? e.g. board members or others?

(also could you look at #58)

**Comment by duemunk** [comment]
No, Ruta should be there. Just have 3+2 and then maybe centered, if that's not too difficult.

**Comment by ksmandersen** [comment]
Can we get a status on this?

**Comment by higiacomo** [comment]
added Ruta https://github.com/bemyeyes/bemyeyes-website/pull/59
![screen shot 2015-07-14 at 11 47 56](https://cloud.githubusercontent.com/assets/874876/8670526/344b8800-2a1e-11e5-971d-8ef5f6792f53.png)

**Comment by ksmandersen** [comment]
Pushed live
