### ISSUE TITLE
Help page without traffic

### ISSUE THREAD

**Issue by higiacomo** [bemyeyes/bemyeyes-website#58]
It looks like the help page isn't getting any traffic
See analytics scree here: http://cl.ly/image/1S2N0E211H11

I suggest
- we redirect after a successful Mailchimp subscription
- eventually even add "help" to the main navigation

**Comment by duemunk** [comment]
Good idea!

We are going to redo the entire flow on the website and design the non-frontpages. But we have to wait a bit until we have some more time to do it right.

**Comment by higiacomo** [comment]
Any chance to put this page to use?
It's 100% ready and can help grow BME

**Comment by duemunk** [comment]
Go

**Comment by ksmandersen** [comment]
Pushed live
