### ISSUE TITLE
Language errors

### ISSUE THREAD

**Issue by idamariepiper** [bemyeyes/bemyeyes-website#64]
I just read the information on your website, and I noticed that you use the phrase "in forehand" a few times. I wanted to let you know that the English word is "beforehand". Although most readers probably know that you mean beforehand, the phrase "in forehand" doesn't mean anything and is never used in the English language. Just thought you might like to know.

**Comment by ksmandersen** [comment]
Thanks :+1: 

Closed in 08d888690760fd89c00fa5b8c2056c0d82963e04

**Comment by ksmandersen** [comment]
Deployed into production
