### ISSUE TITLE
Remove "Status" from the webpage

### ISSUE THREAD

**Issue by idamariepiper** [bemyeyes/bemyeyes-website#66]
The page "Status" is confusing. I dont think I lot of people understand how to read it. So either we need more information to explain, who to understand the status. Otherwise we should just delete it.

**Comment by ksmandersen** [comment]
I agree. Thoughts @duemunk ?

**Comment by duemunk** [comment]
Agree :)

**Comment by Jachobsen** [comment]
Fixed in 5b944b9fb197bc82ce03f9a25e772247012201b6
