### ISSUE TITLE
Update links with media coverage 

### ISSUE THREAD

**Issue by idamariepiper** [bemyeyes/bemyeyes-website#68]
Select the coolest medias. And move the section with the media coverage, so it is right under the section "About Be My Eyes".

**Comment by ksmandersen** [comment]
We need someone to define what is the "coolest" media. Also that list is very outdated. Pretty sure there should a lot more mentions

**Comment by idamariepiper** [comment]
I will do the list within a week. I will post it here.

**Comment by idamariepiper** [comment]
Sorry for the delay! I have created a list. I will send it to you..

**Comment by idamariepiper** [comment]
Sorry for the delay! I have made the list - Excel. Send me an email, and I will send it to you. My mail: ida@bemyeyes.org

**Comment by Jachobsen** [comment]
Fixed in 357362086d838ec3b041b897d02b467f97db6386
