### ISSUE TITLE
Make image for great previews on Facebook & Twitter

### ISSUE THREAD

**Issue by Thelle** [bemyeyes/bemyeyes-website#8]
Would be great if the 'iPhone eyes'-picture would be the one used by default in "Facebook Image Preview"/"Twitter Photo Preview" when sharing.. 
https://developers.facebook.com/docs/sharing/best-practices#images - just like this update: https://www.facebook.com/bemyeyes.org/posts/759825977406015

**Comment by ksmandersen** [comment]
Attach the photo you wan't to use here

**Comment by Thelle** [comment]
![video-thumbnail_cropped facebook](https://cloud.githubusercontent.com/assets/1733883/5701361/4a32e9b0-9a4a-11e4-9174-160d9a5931b9.png)

**Comment by ksmandersen** [comment]
Done
