### ISSUE TITLE
Bigger Available on the AppStore (Nice to have)

### ISSUE THREAD

**Issue by Thelle** [bemyeyes/bemyeyes-website#9]

**Comment by mbogh** [comment]
@Thelle how come it is **Available on the AppStore** and not the official™ **Download on the AppStore**?
If the latter could be accepted, Apple provides [vector graphics](https://developer.apple.com/app-store/marketing/guidelines/#downloadOnAppstore)!

**Comment by ksmandersen** [comment]
Design decision by Flarup. We usually don't use the stock one that Apple provides

**Comment by mbogh** [comment]
Rebels :smile:
